apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-svc
  labels:
    run: udagram-frontend-svc
spec:
  ports:
    - port: 80
      protocol: TCP
  selector: # select pod with label
    app: udagram-frontend
