apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
        - name: udagram-api-feed
          image: manh4real/udagram-api-feed
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secret
            - secretRef:
                name: aws-secret
          volumeMounts:
            - name: aws-credentials
              mountPath: /root/.aws/credentials
              readOnly: true
              subPath: credentials
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "500m"
      volumes:
        - name: aws-credentials
          secret:
            secretName: aws-secret
