version: 2.1
branches:
  only:
    - main
orbs:
  # node: circleci/node@6.2.0
  # eb: circleci/aws-elastic-beanstalk@2.0.1
  # aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    docker:
      - image: "cimg/node:12.13"
    steps:
      # - node/install
      - checkout
      # - aws-cli/setup
      # - eb/setup
      - setup_remote_docker
      - run:
          name: Publish Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker-compose -f docker-compose-build.yaml build --parallel
            docker-compose push
